version: '3'
services:
  users:
    build: "apps/users/"
    volumes:
        - ./apps/users/:/app
    ports:
        - "5001:5000"
    environment:
        - FLASK_ENV=development

  photos:
    build: "apps/photos/"
    volumes:
        - ./apps/photos/:/app
    ports:
        - "5002:5000"
    environment:
        - FLASK_ENV=development

  translate:
    build: "apps/translate/"
    ports:
        - "5003:5000"

  events:
    build: "apps/events/"
    ports:
        - "5004:8000"

  redis-zato:
    image: "redis:alpine"

  zato:
    build: "zato/"
    ports:
        - "8183:8183"
        - "11223:11223"
        - "17010:17010"
        - "17011:17011"
    volumes:
        - ./services/:/incoming/services
    links:
        - users
        - photos 
        - translate
        - events
        - redis-zato

  tests:
      build: "tests/"
      volumes:
        - ./tests/:/app
      command: ["./wait-for-status.sh", "-t", "180", "-i", "20", "-s", "405", "http://zato:11223/users/login/", "--", "behave"]
      links:
          - zato
