version: '3'
services:
  users:
    build: "users/"
    volumes:
        - ./users/:/app
    ports:
        - "5001:5000"
    environment:
        - FLASK_ENV=development

  photos:
    build: "photos/"
    volumes:
        - ./photos/:/app
    ports:
        - "5002:5000"
    environment:
        - FLASK_ENV=development

  translate:
    build: "translate/"
    ports:
        - "5003:5000"

  events:
    build: "events/"
    ports:
        - "5004:8000"

  redis:
    image: "redis:alpine"

  zato:
    build: "zato/"
    ports:
        - "8183:8183"
        - "11223:11223"
        - "17010:17010"
        - "17011:17011"
    volumes:
        - ./services/:/incoming/services
    links:
        - users
        - photos 
        - translate
        - events
        - redis

  test:
      build: "tests/"
      volumes:
        - ./tests/:/app
      links:
          - zato
      command: ["./wait-for-it.sh", "-t", "60", "zato:8183", "--", "behave"]
