version: '3'
services:
  redis:
    image: "redis:alpine"
  ubuntu:
    build: "zato/"
    ports:
        - "8183:8183"
        - "11223:11223"
    entrypoint:
        - "/bin/bash"
        - -c
        - |
            mkdir /opt/zato/example && \
            zato quickstart create /opt/zato/example sqlite redis 6379 --cluster_name zato-example --servers 1 && \
            /opt/zato/example/zato-qs-start.sh && \
            tail -f /opt/zato/example/server1/logs/server.log
    links:
        - redis
