apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
spec:
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: events-reload
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: events
spec:
  ports:
    - port: 8000
  type: ClusterIP
  selector:
    app: events
---
