apiVersion: apps/v1
kind: Deployment
metadata:
  name: photos
spec:
  selector:
    matchLabels:
      app: photos
  template:
    metadata:
      labels:
        app: photos
    spec:
      containers:
        - name: photos
          image: photos-reload
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: photos
spec:
  ports:
    - port: 5000
  type: ClusterIP
  selector:
    app: photos
---

