apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: users-reload
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  ports:
    - port: 5000
  type: ClusterIP
  selector:
    app: users
---
