repos:
    -   repo: git://github.com/pre-commit/pre-commit-hooks
        sha: v1.2.3
        hooks:
        -   id: trailing-whitespace
        -   id: check-added-large-files
            args:
                - --maxkb=128
        -   id: check-ast
        -   id: check-case-conflict
        -   id: check-docstring-first
        -   id: check-json
        -   id: check-merge-conflict
        -   id: check-yaml
        -   id: detect-private-key
        -   id: end-of-file-fixer
        -   id: flake8

    -   repo: git://github.com/Lucas-C/pre-commit-hooks.git
        sha: v1.0.1
        hooks:
        -   id: forbid-crlf

    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        - id: black
          language_version: python3.7
          args: [
              --line-length=79,
              --check,
              --diff
          ]
